version: '3.8'

services:
  backend:
    # IMPORTANTE: Substitua 'seu-usuario-dockerhub' pelo seu usuário do Docker Hub
    image: foco/recrutamentoia-backend:latest
    environment:
      # --- CREDENCIAIS INSERIDAS DIRETAMENTE (NÃO RECOMENDADO) ---
      FRONTEND_URL: "https://recrutamentoia.com.br"
      VITE_BASEROW_API_KEY: "anGucsRrFCKrOmUYHapVYsr5U3FVK85o"
      GOOGLE_CLIENT_ID: "726048519835-4o31uj1ssftc47a08kcb8hs1hkm2v040.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "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"
      GOOGLE_REDIRECT_URI: "https://recrutamentoia.com.br/api/google/auth/callback"
      N8N_SCHEDULE_WEBHOOK_URL: "https://webhook.focoserv.com.br/webhook/googleacesso"
      # A variável N8N_TRIAGEM_WEBHOOK_URL não estava no compose anterior,
      # mas estou adicionando caso o backend precise dela.
      N8N_TRIAGEM_WEBHOOK_URL: "https://webhook.focoserv.com.br/webhook/recrutamento"
    networks:
      - traefik_network
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.recrutamentoai-backend.rule=Host(`recrutamentoia.com.br`) && PathPrefix(`/api`)"
      - "traefik.http.routers.recrutamentoai-backend.entrypoints=websecure"
      - "traefik.http.routers.recrutamentoai-backend.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.recrutamentoai-backend.loadbalancer.server.port=3001"
      - "traefik.http.routers.recrutamentoai-backend.middlewares=sslheader"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"

  frontend:
    # IMPORTANTE: Substitua 'seu-usuario-dockerhub' pelo seu usuário do Docker Hub
    image: seu-usuario-dockerhub/recrutamentoia-frontend:latest
    networks:
      - traefik_network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.recrutamentoai-frontend.rule=Host(`recrutamentoia.com.br`) || Host(`www.recrutamentoia.com.br`)"
      - "traefik.http.routers.recrutamentoai-frontend.entrypoints=websecure"
      - "traefik.http.routers.recrutamentoai-frontend.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.recrutamentoai-frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.recrutamentoai-frontend.middlewares=sslheader"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"

# Como não estamos mais usando secrets, a seção 'secrets' foi removida.

networks:
  traefik_network:
    external: true
    name: Foco