version: '3.8'

services:
  backend:
    image: orickjogando/recrutamentoia-backend:latest
    # Se você optou por colocar as variáveis aqui, mantenha a seção 'environment'.
    # Se optou por usar "secrets", mantenha a seção 'secrets'.
    # Vou manter a versão com 'environment' que foi a última que configuramos.
    environment:
      FRONTEND_URL: "https://recrutamentoia.com.br"
      VITE_BASEROW_API_KEY: "anGucsRrFCKrOmUYHapVYsr5U3FVK85o"
      GOOGLE_CLIENT_ID: "726048519835-4o31uj1ssftc47a08kcb8hs1hkm2v040.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "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"
      GOOGLE_REDIRECT_URI: "https://recrutamentoia.com.br/api/google/auth/callback"
      N8N_SCHEDULE_WEBHOOK_URL: "https://webhook.focoserv.com.br/webhook/googleacesso"
      N8N_TRIAGEM_WEBHOOK_URL: "https://webhook.focoserv.com.br/webhook/recrutamento"
    networks:
      - traefik_network
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      # --- ADICIONADO AQUI ---
      resources:
        limits:
          cpus: '0.50' # Limita o uso a 50% de um núcleo de CPU
          memory: 512M # Limita o uso de memória a 512 Megabytes
      # --- FIM DA ADIÇÃO ---
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.recrutamentoai-backend.rule=Host(`recrutamentoia.com.br`) && PathPrefix(`/api`)"
      # ... (resto das labels continua igual)

  frontend:
    image: orickjogando/recrutamentoia-frontend:latest
    networks:
      - traefik_network
    deploy:
      replicas: 1
      # --- ADICIONADO AQUI ---
      resources:
        limits:
          cpus: '0.25' # Limita a 25% de um núcleo (frontend usa menos)
          memory: 256M # Limita a 256 Megabytes
      # --- FIM DA ADIÇÃO ---
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.recrutamentoai-frontend.rule=Host(`recrutamentoia.com.br`) || Host(`www.recrutamentoia.com.br`)"
      # ... (resto das labels continua igual)

networks:
  traefik_network:
    external: true
    name: foco