version: '3.8'

services:
  backend:
    image: orickjogando/recrutamentoia-backend:latest
    environment:
      FRONTEND_URL: "https://recrutamentoia.com.br"
      VITE_BASEROW_API_KEY: "anGucsRrFCKrOmUYHapVYsr5U3FVK85o"
      GOOGLE_CLIENT_ID: "726048519835-4o31uj1ssftc47a08kcb8hs1hkm2v040.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "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"
      GOOGLE_REDIRECT_URI: "https://recrutamentoia.com.br/api/google/auth/callback"
      N8N_SCHEDULE_WEBHOOK_URL: "https://webhook.focoserv.com.br/webhook/googleacesso"
      N8N_TRIAGEM_WEBHOOK_URL: "https://webhook.focoserv.com.br/webhook/recrutamento"
    # --- MUDANÇA IMPORTANTE AQUI ---
    ports:
      - "3001:3001"
    networks:
      - traefik_network
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
    # LABELS DO TRAEFIK REMOVIDAS DO BACKEND

  frontend:
    image: orickjogando/recrutamentoia-frontend:latest
    networks:
      - traefik_network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
    labels:
      # As labels do frontend continuam, pois ele está funcionando
      - "traefik.enable=true"
      - "traefik.http.routers.recrutamentoai-frontend.rule=Host(`recrutamentoia.com.br`) || Host(`www.recrutamentoia.com.br`)"
      - "traefik.http.routers.recrutamentoai-frontend.priority=50"
      - "traefik.http.routers.recrutamentoai-frontend.entrypoints=websecure"
      - "traefik.http.routers.recrutamentoai-frontend.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.recrutamentoai-frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.recrutamentoai-frontend.middlewares=sslheader"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"

networks:
  traefik_network:
    external: true
    name: Foco