version: '3.8'

services:
  backend:
    container_name: recrutamentoai-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.recrutamentoai-backend.rule=Host(`recrutamentoia.com.br`) && PathPrefix(`/api`)"
      - "traefik.http.routers.recrutamentoai-backend.entrypoints=websecure"
      - "traefik.http.routers.recrutamentoai-backend.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.recrutamentoai-backend.loadbalancer.server.port=3001"
      - "traefik.http.routers.recrutamentoai-backend.middlewares=sslheader"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"

  frontend:
    container_name: recrutamentoai-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.recrutamentoai-frontend.rule=Host(`recrutamentoia.com.br`) || Host(`www.recrutamentoia.com.br`)"
      - "traefik.http.routers.recrutamentoai-frontend.entrypoints=websecure"
      - "traefik.http.routers.recrutamentoai-frontend.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.recrutamentoai-frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.recrutamentoai-frontend.middlewares=sslheader"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"

networks:
  traefik_network:
    external: true
    name: foco